export const products = [
    { id: 1, name: 'Arabica Whole Beans', category: 'Whole Beans', price: '$20', image: '/images/beans.jpg' },
    { id: 2, name: 'Robusta Whole Beans', category: 'Whole Beans', price: '$18', image: '/images/beans.jpg' },
    { id: 3, name: 'Ground Arabica Coffee', category: 'Ground Coffee', price: '$15', image: '/images/ground.jpg' },
    { id: 4, name: 'Ground Robusta Coffee', category: 'Ground Coffee', price: '$12', image: '/images/ground.jpg' },
    { id: 5, name: 'Milk', category: 'Milk', price: '$3', image: '/images/milk.jpg' },
    { id: 6, name: 'DeLonghi Coffee Machine', category: 'Coffee Machines', price: '$300', image: '/images/coffee_machine.jpg' },
    { id: 7, name: 'Ceramic Mug', category: 'Mugs', price: '$10', image: '/images/mug.jpg' },
    { id: 8, name: 'Metal Pitcher', category: 'Pitchers', price: '$25', image: '/images/pitcher.jpg' },
    { id: 9, name: 'Espresso Beans', category: 'Whole Beans', price: '$22', image: '/images/espresso_beans.jpg' },
    { id: 10, name: 'Dark Roast Coffee', category: 'Ground Coffee', price: '$16', image: '/images/dark_roast.jpg' },
    { id: 11, name: 'Coconut Milk', category: 'Milk', price: '$4', image: '/images/coconut_milk.jpg' },
    { id: 12, name: 'French Press', category: 'Coffee Machines', price: '$30', image: '/images/french_press.jpg' },
    { id: 13, name: 'Glass Mug', category: 'Mugs', price: '$12', image: '/images/glass_mug.jpg' },
    { id: 14, name: 'Coffee Grinder', category: 'Coffee Machines', price: '$50', image: '/images/coffee_grinder.jpg' },
    { id: 15, name: 'Flavored Ground Coffee', category: 'Ground Coffee', price: '$14', image: '/images/flavored_coffee.jpg' },
    { id: 16, name: 'Oat Milk', category: 'Milk', price: '$5', image: '/images/oat_milk.jpg' },
    { id: 17, name: 'Pour Over Coffee Maker', category: 'Coffee Machines', price: '$25', image: '/images/pour_over.jpg' },
    { id: 18, name: 'Travel Mug', category: 'Mugs', price: '$15', image: '/images/travel_mug.jpg' },
    { id: 19, name: 'Arabica Coffee Beans', category: 'Whole Beans', price: '$19', image: '/images/arabica_coffee.jpg' },
    { id: 20, name: 'Decaf Ground Coffee', category: 'Ground Coffee', price: '$17', image: '/images/decaf_coffee.jpg' },
    { id: 21, name: 'Soy Milk', category: 'Milk', price: '$4', image: '/images/soy_milk.jpg' },
    { id: 22, name: 'AeroPress', category: 'Coffee Machines', price: '$40', image: '/images/aeropress.jpg' },
    { id: 23, name: 'Enamel Mug', category: 'Mugs', price: '$11', image: '/images/enamel_mug.jpg' },
    { id: 24, name: 'Blend of the Month', category: 'Whole Beans', price: '$25', image: '/images/blend_of_month.jpg' },
    { id: 25, name: 'Hazelnut Ground Coffee', category: 'Ground Coffee', price: '$16', image: '/images/hazelnut_coffee.jpg' },
    { id: 26, name: 'Almond Milk', category: 'Milk', price: '$5', image: '/images/almond_milk.jpg' },
    { id: 27, name: 'Espresso Machine', category: 'Coffee Machines', price: '$500', image: '/images/espresso_machine.jpg' },
    { id: 28, name: 'Double-Wall Mug', category: 'Mugs', price: '$18', image: '/images/double_wall_mug.jpg' },
    { id: 29, name: 'Coffee Blend', category: 'Whole Beans', price: '$24', image: '/images/coffee_blend.jpg' },
    { id: 30, name: 'Caramel Ground Coffee', category: 'Ground Coffee', price: '$15', image: '/images/caramel_coffee.jpg' },
    { id: 31, name: 'Cashew Milk', category: 'Milk', price: '$5', image: '/images/cashew_milk.jpg' },
    { id: 32, name: 'Turkish Coffee Pot', category: 'Coffee Machines', price: '$35', image: '/images/turkish_coffee_pot.jpg' },
    { id: 33, name: 'Insulated Mug', category: 'Mugs', price: '$20', image: '/images/insulated_mug.jpg' },
    { id: 34, name: 'Peruvian Coffee Beans', category: 'Whole Beans', price: '$22', image: '/images/peruvian_coffee.jpg' },
    { id: 35, name: 'Vanilla Ground Coffee', category: 'Ground Coffee', price: '$15', image: '/images/vanilla_coffee.jpg' },
    { id: 36, name: 'Goat Milk', category: 'Milk', price: '$6', image: '/images/goat_milk.jpg' },
    { id: 37, name: 'Cold Brew Coffee Maker', category: 'Coffee Machines', price: '$45', image: '/images/cold_brew_maker.jpg' },
    { id: 38, name: 'Bamboo Mug', category: 'Mugs', price: '$14', image: '/images/bamboo_mug.jpg' },
    { id: 39, name: 'Italian Roast Whole Beans', category: 'Whole Beans', price: '$21', image: '/images/italian_roast.jpg' },
    { id: 40, name: 'Cinnamon Ground Coffee', category: 'Ground Coffee', price: '$15', image: '/images/cinnamon_coffee.jpg' },
];


export default products;